//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitteamClientViewer.GitteamServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GitteamServices.ICommandGitService")]
    public interface ICommandGitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandGitService/FindNoCommitedFiles", ReplyAction="http://tempuri.org/ICommandGitService/FindNoCommitedFilesResponse")]
        string FindNoCommitedFiles();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommandGitServiceChannel : GitteamClientViewer.GitteamServices.ICommandGitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommandGitServiceClient : System.ServiceModel.ClientBase<GitteamClientViewer.GitteamServices.ICommandGitService>, GitteamClientViewer.GitteamServices.ICommandGitService {
        
        public CommandGitServiceClient() {
        }
        
        public CommandGitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommandGitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandGitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandGitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string FindNoCommitedFiles() {
            return base.Channel.FindNoCommitedFiles();
        }
    }
}
